appname: cityLog

db:
    name:     gotest
    user:     root
    password: root
    port:     3306
    host:     127.0.0.1
    option:   charset=utf8&parseTime=True

mdb:
  name: logman
  url:  127.0.0.1
  port: 27017


key: 123
